// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD05Dh_lXjYtqieqvWtGv1agmcaswr9-2U',
    appId: '1:400731025695:web:acb8c46e55cc835b71c02a',
    messagingSenderId: '400731025695',
    projectId: 'notesapp-dheerajmurthy',
    authDomain: 'notesapp-dheerajmurthy.firebaseapp.com',
    storageBucket: 'notesapp-dheerajmurthy.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCOv86qRZ0lwgBxydpA6Jjb0j-zqF8Qow',
    appId: '1:400731025695:android:c111eafc9d4e92fa71c02a',
    messagingSenderId: '400731025695',
    projectId: 'notesapp-dheerajmurthy',
    storageBucket: 'notesapp-dheerajmurthy.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7K8TJAVq1zpfXQKbezdy_73c_xe-j3oQ',
    appId: '1:400731025695:ios:d661e5fad4f7c08f71c02a',
    messagingSenderId: '400731025695',
    projectId: 'notesapp-dheerajmurthy',
    storageBucket: 'notesapp-dheerajmurthy.appspot.com',
    iosBundleId: 'com.msdheerajmurthy.notesapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7K8TJAVq1zpfXQKbezdy_73c_xe-j3oQ',
    appId: '1:400731025695:ios:fd045191d4fcd07671c02a',
    messagingSenderId: '400731025695',
    projectId: 'notesapp-dheerajmurthy',
    storageBucket: 'notesapp-dheerajmurthy.appspot.com',
    iosBundleId: 'com.msdheerajmurthy.notesapp.RunnerTests',
  );
}
